---
# defaults file for addons

# determines if we are on the first master instance.
is_first_master: "{% if inventory_hostname == groups['masters'][0] %}true{% else %}false{% endif %}"

# skydns
dns_replicas: 1

kubectl_bin: /opt/bin/kubectl
