---
# SkyDNS service addon
- name: create SkyDNS pod file
  become: yes
  template:
    src: skydns-rc.yaml.j2
    dest: "{{ kubernetes_addons_dir }}/skydns-rc.yaml"
  tags:
    - addons
    - skydns

- name: create SkyDNS service file
  become: yes
  template:
    src: skydns-svc.yaml.j2
    dest: "{{ kubernetes_addons_dir }}/skydns-svc.yaml"
  tags:
    - addons
    - skydns

- name: Create SkyDNS replication controller
  become: yes
  kube:
    resource: rc
    name: kube-dns-v9
    namespace: kube-system
    filename: "{{ kubernetes_addons_dir }}/skydns-rc.yaml"
    state: present
  tags:
    - addons
    - skydns

- name: Create SkyDNS service
  become: yes
  kube:
    resource: svc
    name: kube-dns
    namespace: kube-system
    filename: "{{ kubernetes_addons_dir }}/skydns-svc.yaml"
    state: present
  tags:
    - addons
    - skydns
